/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Books.windows;

import Books.table.models.BooksTableModel;
import Database.util.DatabaseHelper;
import Database.util.SearchHelper;
import boooks.objects.Book;
import boooks.objects.User;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import util.pdf.GeneratePDF;

/**
 *
 * @author mbaiu
 */
public class AddBooksWindow extends javax.swing.JFrame {
    private static final List<String> gradeList=new ArrayList<>(Arrays.asList(new String[]{"KG1", "KG2", "KG3", "GR1", "GR2", "GR3", "GR4", "GR5", "GR6", "GR7", "GR8", "GR9"}));
    private static final List<String> subjectList=new ArrayList<>(Arrays.asList(new String[]{"Arabic","Computer","English","French","Islamic","Math","Science","Social"}));
    
    /**
     * Creates new form AddBooks
     */
    private BooksTableModel tableModel = new BooksTableModel();
    private ArrayList<Book> booksList = new ArrayList<>();
    
    
    private static User USER;

    public AddBooksWindow() {
        initComponents();
//        ImageIcon icon = new ImageIcon("resources/logo.png");
        ImageIcon icon = new ImageIcon(getClass().getResource("/logos/Sunrise.png"));
        this.setIconImage(icon.getImage());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        this.setExtendedState( this.getExtendedState()|JFrame.MAXIMIZED_BOTH );
        this.jTableBooks.setModel(tableModel);
        
        TableColumnModel tcm = jTableBooks.getColumnModel();
        TableColumn col = tcm.getColumn(8);
        tcm.removeColumn(col);

        
//        calculatePrice();
        clearTextFields(true);
        
    }
    public void setUser(User user){
        this.USER= user;
        this.booksList=SearchHelper.getBooks();
        this.tableModel.setData(this.booksList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jTextFieldQty = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCost = new javax.swing.JTextField();
        jComboBoxGrade = new javax.swing.JComboBox<>();
        jComboBoxSubject = new javax.swing.JComboBox<>();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabelBookName = new javax.swing.JLabel();
        jButtonBarcodes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBooks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAdd.setText("Add");
        jButtonAdd.setToolTipText("");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jTextFieldID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIDKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Title");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Subject:");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel5.setText("Grade:");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Qty:");

        jTextFieldTitle.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jTextFieldQty.setEditable(false);
        jTextFieldQty.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextFieldQty.setForeground(new java.awt.Color(51, 0, 204));
        jTextFieldQty.setText("0");
        jTextFieldQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtyActionPerformed(evt);
            }
        });

        jButtonClear.setForeground(new java.awt.Color(255, 153, 51));
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setText("Price:");

        jTextFieldCost.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextFieldCost.setText("0");
        jTextFieldCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCostActionPerformed(evt);
            }
        });

        jComboBoxGrade.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jComboBoxGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG1", "KG2", "KG3", "GR1", "GR2", "GR3", "GR4", "GR5", "GR6", "GR7", "GR8", "GR9" }));

        jComboBoxSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arabic","Computer","English","French","Islamic","Math","Science","Social"}));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTitle)
                                    .addComponent(jTextFieldID)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(14, 14, 14)
                                .addComponent(jTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSubject, 0, 140, Short.MAX_VALUE)
                        .addGap(133, 133, 133))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGrade, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClear))
                .addGap(89, 89, 89))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabelBookName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelBookName.setToolTipText(" ");

        jButtonBarcodes.setText("Get Barcodes");
        jButtonBarcodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBarcodesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBarcodes, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBookName, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBarcodes)
                .addContainerGap())
        );

        jSplitPane2.setTopComponent(jPanel3);

        jTableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableBooks.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableBooks);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel4);

        jSplitPane1.setRightComponent(jSplitPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        Book book= new Book();
        book.setId(jTextFieldID.getText());
        book.setTitle(jTextFieldTitle.getText());
        book.setGrade(jComboBoxGrade.getSelectedItem().toString());
        book.setSubject(jComboBoxSubject.getSelectedItem().toString());
        book.setQty(0);
        book.setCost(Double.valueOf(jTextFieldCost.getText()));
//        book.setCostDiscountRate(Double.valueOf(jTextFieldCostDiscount.getText()));
//        book.setProfitRate(Double.valueOf(jTextFieldProfitRate.getText()));
        if(jButtonAdd.getText().equals("Add")){
            DatabaseHelper.addBook(book);
        }
        else if(jButtonAdd.getText().equals("Update")){
            DatabaseHelper.updateBook(book);
        }
        System.out.println("hey");
        
        
        
        
        this.booksList=SearchHelper.getBooks();
        this.tableModel.setData(this.booksList);
        clearTextFields(true);

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            
//            this.jLabel1.setText(this.jTextFieldID.getText());
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDKeyPressed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        clearTextFields(true);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTextFieldCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostActionPerformed

    private void jTextFieldIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKeyReleased
        // TODO +++++++++++++++++++
        
        int bookIndex = this.booksList.indexOf(new Book(this.jTextFieldID.getText()));
            if(bookIndex==-1){ //id not found in list
                clearTextFields(false);
                
                this.jButtonAdd.setText("Add");
                this.jLabelBookName.setText("Not found!");
            }
            else{
                bookLookUpWithIndex(bookIndex);
                
            }
    }//GEN-LAST:event_jTextFieldIDKeyReleased

    private void jTextFieldQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtyActionPerformed

    private void jButtonBarcodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBarcodesActionPerformed
        List<Book> booksToHaveBarcodes = new ArrayList<>();
        for (int i = 0; i < jTableBooks.getRowCount(); i++) {
            if((Boolean)jTableBooks.getModel().getValueAt(i, 7)){
                booksToHaveBarcodes.add((Book) jTableBooks.getModel().getValueAt(i, 8));
            }
            // do something with the values...
        }
        if(!booksToHaveBarcodes.isEmpty()){
                GeneratePDF.createBarcodesPdf(booksToHaveBarcodes);
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBarcodesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooksWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBarcodes;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JComboBox<String> jComboBoxGrade;
    private javax.swing.JComboBox<String> jComboBoxSubject;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBookName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTable jTableBooks;
    private javax.swing.JTextField jTextFieldCost;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldQty;
    private javax.swing.JTextField jTextFieldTitle;
    // End of variables declaration//GEN-END:variables
    
    
    private void bookLookUpWithIndex(int bookIndex){
        this.jTableBooks.changeSelection(bookIndex, 0, false, false);
        Book book = this.booksList.get(bookIndex);
        this.jLabelBookName.setText(book.getTitle());
        this.jButtonAdd.setText("Update");
        this.jTextFieldTitle.setText(book.getTitle());
        System.out.println("Grade:"+ book.getGrade());
        this.jComboBoxGrade.setSelectedIndex(gradeList.indexOf(book.getGrade()));
        this.jComboBoxSubject.setSelectedIndex(subjectList.indexOf(book.getSubject()));
        this.jTextFieldQty.setText(String.valueOf(book.getQty()));
//        this.jTextFieldPrice.setText(String.valueOf(book.getPrice()));
        this.jTextFieldCost.setText(String.valueOf(book.getCost()));
//        this.jTextFieldCostDiscount.setText(String.valueOf(book.getCostDiscountRate()));
//        this.jTextFieldProfitRate.setText(String.valueOf(book.getProfitRate()));
    }
//    private void calculatePrice(){
//        jTextFieldCost.setText("0");
//        jTextFieldCost.addKeyListener(new KeyListener() {
//            @Override
//            public void keyTyped(KeyEvent e) {
//            }
//            @Override
//            public void keyPressed(KeyEvent e) {
//                if(jTextFieldCost.getText().equals("0") || jTextFieldCost.getText().equals("0.0")){
//                    jTextFieldCost.setText("");
//                }
//            }
//
//            @Override
//            public void keyReleased(KeyEvent e) {
//                if(jTextFieldCost.getText().equals("")){
//                    jTextFieldCost.setText("0");
//                }
//                else{
//                    double cost = Double.valueOf(jTextFieldCost.getText());
////                    double discRate = Double.valueOf(jTextFieldCostDiscount.getText())/100;
////                    double profitRate = 1+(Double.valueOf(jTextFieldProfitRate.getText())/100);
////                    double price=cost*discRate*profitRate;
////                    jTextFieldPrice.setText(String.valueOf(price));
//                }
//                
//            }
//        });
//        jTextFieldCostDiscount.setText("0");
//        jTextFieldCostDiscount.addKeyListener(new KeyListener() {
//            @Override
//            public void keyTyped(KeyEvent e) {
//            }
//            @Override
//            public void keyPressed(KeyEvent e) {
//                if(jTextFieldCostDiscount.getText().equals("0") || jTextFieldCostDiscount.getText().equals("0.0")){
//                    jTextFieldCostDiscount.setText("");
//                }
//            }
//
//            @Override
//            public void keyReleased(KeyEvent e) {
//                if(jTextFieldCostDiscount.getText().equals("")){
//                    jTextFieldCostDiscount.setText("0");
//                }
//                else{
//                    double cost = Double.valueOf(jTextFieldCost.getText());
//                    double discRate = Double.valueOf(jTextFieldCostDiscount.getText())/100;
//                    double profitRate = 1+(Double.valueOf(jTextFieldProfitRate.getText())/100);
//                    double price=cost*discRate*profitRate;
//                    jTextFieldPrice.setText(String.valueOf(price));
//                }
//                
//            }
//        });
//        jTextFieldProfitRate.setText("0");
//        jTextFieldProfitRate.addKeyListener(new KeyListener() {
//            @Override
//            public void keyTyped(KeyEvent e) {
//            }
//            @Override
//            public void keyPressed(KeyEvent e) {
//                if(jTextFieldProfitRate.getText().equals("0") || jTextFieldProfitRate.getText().equals("0.0")){
//                    jTextFieldProfitRate.setText("");
//                }
//            }
//
//            @Override
//            public void keyReleased(KeyEvent e) {
//                if(jTextFieldProfitRate.getText().equals("")){
//                    jTextFieldProfitRate.setText("0");
//                }
//                else{
//                    double cost = Double.valueOf(jTextFieldCost.getText());
//                    double discRate = Double.valueOf(jTextFieldCostDiscount.getText())/100;
//                    double profitRate = 1+(Double.valueOf(jTextFieldProfitRate.getText())/100);
//                    double price=cost*discRate*profitRate;
//                    jTextFieldPrice.setText(String.valueOf(price));
//                }
//                
//            }
//        });
//    }
    private void clearTextFields(boolean clearID) {
        if(clearID){
            jTextFieldID.setText("");
        }
        jLabelBookName.setText("");
        jTextFieldTitle.setText("");
        jComboBoxGrade.setSelectedIndex(-1);
        jComboBoxSubject.setSelectedIndex(-1);
        jTextFieldCost.setText("0");
//        jTextFieldCostDiscount.setText("0");
//        jTextFieldProfitRate.setText("0");
        jTextFieldQty.setText("0");
//        jTextFieldPrice.setText("0");
        jButtonAdd.setText("Add");
    }
}