/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Books.windows;

import App.users.UsersWindow;
import Books.inventory.windows.InventoryWindow;
import Books.sale.windows.SalesWindow;
import Database.util.DatabaseBuilder;
import Database.util.DatabaseHelper;
import Database.util.SearchHelper;
import boooks.objects.User;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import util.pdf.BarcodeGenerator;
import util.pdf.excel.ExcelHelper;
import util.pdf.excel.ExcelJDialog;

/**
 *
 * @author mbaiu
 */
public class MainBooksWindow extends javax.swing.JFrame {
    public static final String xUser="Admin";
    public static final String xPass="pass";
    private AddBooksWindow addBooksWindow;
    private BookListWindow bookListWindow;
    private InventoryWindow invWindow;
    private UsersWindow usersWindow;
    private SalesWindow salesWindow;
    public User USER;
    
    public MainBooksWindow() {
        initComponents();
        jButtonBookList.setEnabled(false);
//        BarcodeGenerator.creadeBarCode();
        DatabaseBuilder.createAllTables();
//        addBooksWindow= new AddBooksWindow();
//        invWindow= new InventoryWindow();
//        usersWindow= new UsersWindow();
//        salesWindow= new SalesWindow();
        logout();
        this.jDialogLogIn.setDefaultLookAndFeelDecorated(false);
        
        
        
        BufferedImage bf = new BufferedImage(1,1,BufferedImage.TYPE_INT_ARGB);
        bf.setRGB(0, 0, new Color(1f,0f,0f,.5f ).getRGB());

//        this.setIconImage(bf);
//        this.jDialogLogIn.setIconImage(bf);
//        ImageIcon icon = new ImageIcon("resources/logo.png");
        ImageIcon icon = new ImageIcon(getClass().getResource("/logos/Sunrise.png"));

        this.setIconImage(icon.getImage());
        this.jDialogLogIn.setIconImage(icon.getImage());
        String currentDirectory = System.getProperty("user.dir");
System.out.println("Current working directory: " + currentDirectory);
        this.setTitle("Sunrise schools");
        
        
        
        

        
        this.setExtendedState( this.getExtendedState()|JFrame.MAXIMIZED_BOTH );
//        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
//        this.addWindowListener(getWindowAdapter());

        //pack frame (size JFrame to match preferred sizes of added components and set visible
        this.pack();
        this.setVisible(true);
        
        
//        this.setResizable(false);
//        this.set
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogLogIn = new javax.swing.JDialog();
        jComboBoxLoginUser = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonBooks = new javax.swing.JButton();
        jButtonInventory = new javax.swing.JButton();
        jButtonSales = new javax.swing.JButton();
        jButtonUsers = new javax.swing.JButton();
        jLabelUserName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonBookList = new javax.swing.JButton();

        jDialogLogIn.setAlwaysOnTop(true);

        jComboBoxLoginUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLoginUserActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("User:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Code:");

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jDialogLogInLayout = new javax.swing.GroupLayout(jDialogLogIn.getContentPane());
        jDialogLogIn.getContentPane().setLayout(jDialogLogInLayout);
        jDialogLogInLayout.setHorizontalGroup(
            jDialogLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLogInLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(jDialogLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxLoginUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );
        jDialogLogInLayout.setVerticalGroup(
            jDialogLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLogInLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jDialogLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jDialogLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBooks.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonBooks.setText("Books");
        jButtonBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBooksActionPerformed(evt);
            }
        });

        jButtonInventory.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonInventory.setText("Inventory");
        jButtonInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInventoryActionPerformed(evt);
            }
        });

        jButtonSales.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonSales.setText("Sales");
        jButtonSales.setActionCommand("????? ?????");
        jButtonSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalesActionPerformed(evt);
            }
        });

        jButtonUsers.setText("Users");
        jButtonUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsersActionPerformed(evt);
            }
        });

        jLabelUserName.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabelUserName.setText("Logged out!");

        jButton1.setText("Excel");
        jButton1.setFocusCycleRoot(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonLogout.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonBookList.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonBookList.setText("Book List");
        jButtonBookList.setEnabled(false);
        jButtonBookList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelUserName))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(119, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButtonSales, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBookList, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonBooks, jButtonInventory, jButtonSales, jButtonUsers});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButtonSales, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBookList, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(45, 45, 45)
                .addComponent(jButtonUsers)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonBooks, jButtonInventory, jButtonSales, jButtonUsers});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBooksActionPerformed
        // TODO add your handling code here:
        this.addBooksWindow = new AddBooksWindow();
        this.addBooksWindow.setUser(USER);
        this.addBooksWindow.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_jButtonBooksActionPerformed

    private void jButtonInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInventoryActionPerformed
        // TODO add your handling code here:
        invWindow = new InventoryWindow();
        invWindow.setUser(USER);
        invWindow.setVisible(true);
    }//GEN-LAST:event_jButtonInventoryActionPerformed

    private void jButtonUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsersActionPerformed
        // TODO add your handling code here:
        usersWindow = new UsersWindow();
        usersWindow.setUser(USER);
        usersWindow.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_jButtonUsersActionPerformed

    private void jComboBoxLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLoginUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLoginUserActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        
        closeAllWindows();
        logout();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalesActionPerformed
        // TODO add your handling code here:
        salesWindow = new SalesWindow();
        salesWindow.setUser(USER);
        salesWindow.setVisible(true);
    }//GEN-LAST:event_jButtonSalesActionPerformed

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            boolean found=false;
            if(new String(jPasswordField.getPassword()).equals(xPass) && jComboBoxLoginUser.getSelectedItem().toString().equals(xUser)){
                USER= new User(xUser, xPass,"","",true,true,true,true,true);
                found=true;
                
            }
            else{
                List<User> users=SearchHelper.getUsers();
                User toCheckUser = new User(jComboBoxLoginUser.getSelectedItem().toString(),String.valueOf(jPasswordField.getPassword()));
                if(users.contains(toCheckUser)){
                    USER=users.get(users.indexOf(toCheckUser));
                    found=true;
                }
            }
            if(found){
                this.setTitle("Sunrise schools: "+USER.getId());
                this.jLabelUserName.setText(USER.getId());
                this.jButtonBooks.setEnabled(USER.isAccessBooks());
                this.jButtonSales.setEnabled(USER.isAccessSales());
                this.jButtonInventory.setEnabled(USER.isAccessInventory());
                this.jButtonUsers.setEnabled(USER.isAccessUsers());
//                this.jButtonBookList.setEnabled(USER.isAccessBookLists());
                
                this.jButtonLogout.setEnabled(true);
                this.jDialogLogIn.setVisible(false);
            }
            
        }
    }//GEN-LAST:event_jPasswordFieldKeyPressed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExcelJDialog excelJDialog = new ExcelJDialog(this, rootPaneCheckingEnabled);
        excelJDialog.setUser(USER);
        excelJDialog.setVisible(rootPaneCheckingEnabled);
        // TODO add your handling code here:
//        ExcelHelper.readExcel2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookListActionPerformed
        // TODO add your handling code here:
        this.bookListWindow = new BookListWindow();
        this.bookListWindow.setUser(USER);
        this.bookListWindow.setVisible(true);
    }//GEN-LAST:event_jButtonBookListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBooksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBooksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBooksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBooksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBooksWindow().setVisible(true);
            }
        });
    }
    
    
     private WindowAdapter getWindowAdapter() {

        return new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {//overrode to show message
                super.windowClosing(we);

                JOptionPane.showMessageDialog(MainBooksWindow.this, "Cant Exit");
            }

            @Override
            public void windowIconified(WindowEvent we) {
                MainBooksWindow.this.setState(JFrame.NORMAL);
                JOptionPane.showMessageDialog(MainBooksWindow.this, "Cant Minimize");
            }
        };
    }
    private void logout(){
        //close windows
//        this.addBooksWindow.setVisible(false);
//        this.invWindow.setVisible(false);
//        this.usersWindow.setVisible(false);
//        this.salesWindow.setVisible(false);
        
        //disable buttons
        this.jButtonLogout.setEnabled(false);
        this.jButtonBooks.setEnabled(false);
        this.jButtonInventory.setEnabled(false);
        this.jButtonSales.setEnabled(false);
        this.jButtonUsers.setEnabled(false);
        this.jButtonBookList.setEnabled(false);
        
        this.jLabelUserName.setText("Logged out!");
        this.jPasswordField.setText("");
        
        //show back login dialog
        this.jComboBoxLoginUser.removeAllItems();
        this.jComboBoxLoginUser.addItem(xUser);
        List<String> users=SearchHelper.getAllUserIDs();
        for(String user:users){
            this.jComboBoxLoginUser.addItem(user);
        }
        
        this.jDialogLogIn.setVisible(true);
        this.jDialogLogIn.setSize(400, 400);
        this.jDialogLogIn.setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JButton jButtonBookList;
    javax.swing.JButton jButtonBooks;
    javax.swing.JButton jButtonInventory;
    javax.swing.JButton jButtonLogout;
    javax.swing.JButton jButtonSales;
    javax.swing.JButton jButtonUsers;
    javax.swing.JComboBox<String> jComboBoxLoginUser;
    javax.swing.JDialog jDialogLogIn;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabelUserName;
    javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables

    private void closeAllWindows() {
        if(addBooksWindow==null)
            addBooksWindow= new AddBooksWindow();
        if(invWindow==null)
            invWindow= new InventoryWindow();
        if(usersWindow==null)
            usersWindow= new UsersWindow();
        if(salesWindow==null)
            salesWindow= new SalesWindow();
        if(bookListWindow==null)
            bookListWindow= new BookListWindow();
        this.addBooksWindow.setVisible(false);
        this.invWindow.setVisible(false);
        this.usersWindow.setVisible(false);
        this.salesWindow.setVisible(false);
        this.bookListWindow.setVisible(false);
    }
}
