/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Books.sale.windows;

import Books.sale.dialogs.InvoicesHistoryListJDialog;
import Books.windows.MainBooksWindow;
import Database.util.DatabaseHelper;
import Database.util.SearchHelper;
import boooks.objects.Book;
import boooks.objects.SaleItem;
import boooks.objects.User;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.SortedMap;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mbaiu
 */
public class SalesWindow extends javax.swing.JFrame {

    /**
     * Creates new form SalesWindow
     */
    User USER;
    private DefaultTableModel salesTableModel;
    SortedMap<String,SortedMap<String,List<SaleItem>>> salesHistory;
    public SalesWindow() {
        initComponents();
//        BufferedImage bf = new BufferedImage(1,1,BufferedImage.TYPE_INT_ARGB);
//        bf.setRGB(0, 0, new Color(1f,0f,0f,.5f ).getRGB());
//        this.setIconImage(bf);
//        ImageIcon icon = new ImageIcon("resources/logo.png");
        ImageIcon icon = new ImageIcon(getClass().getResource("/logos/Sunrise.png"));
        this.setIconImage(icon.getImage());
        
        this.jButtonFinish.setEnabled(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        String[] tableHeaders={"Book ID","Title","Qty","price"};
        salesTableModel=new DefaultTableModel(tableHeaders,0){
            @Override
            public boolean isCellEditable(int row, int column) {   
                if(column!=2)
                    return false;
                else
                    return true;
            }
        };
        this.jTableSale.setModel(salesTableModel);
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jButtonRemove = new javax.swing.JButton();
        jButtonClearAll = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSale = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jButtonFinish = new javax.swing.JButton();
        jTextFieldPurchaseID = new javax.swing.JTextField();
        jTextFieldBookID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldQty = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPaneHistory = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setMinimumSize(new java.awt.Dimension(0, 100));

        jButtonRemove.setText("Remove");
        jButtonRemove.setMinimumSize(new java.awt.Dimension(0, 28));
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jButtonClearAll.setText("Clear All");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 572, Short.MAX_VALUE)
                .addComponent(jButtonClearAll)
                .addGap(25, 25, 25))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        jTableSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSale.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSale);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        jButtonFinish.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonFinish.setText("Finish");
        jButtonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishActionPerformed(evt);
            }
        });

        jTextFieldPurchaseID.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextFieldPurchaseID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPurchaseIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPurchaseIDKeyReleased(evt);
            }
        });

        jTextFieldBookID.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextFieldBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBookIDActionPerformed(evt);
            }
        });
        jTextFieldBookID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBookIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBookIDKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Phone Number:");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Book ID:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Qty:");

        jTextFieldQty.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextFieldQty.setText("1");
        jTextFieldQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldQtyFocusLost(evt);
            }
        });
        jTextFieldQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtyActionPerformed(evt);
            }
        });
        jTextFieldQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldQtyKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBookID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPurchaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 761, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPurchaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addComponent(jButtonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jSplitPane1.setRightComponent(jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        jTabbedPane1.addTab("Sale", jPanel2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneHistory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneHistory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("History", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinishActionPerformed
        finishSale();
        fillHistoryTable();
    }//GEN-LAST:event_jButtonFinishActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jTextFieldBookIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBookIDKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Book book = null;
            if(!this.jTextFieldBookID.getText().equals("")){
                book=SearchHelper.getBookByID(this.jTextFieldBookID.getText());
            }
            else{
//                this.jTextFieldBookID.setBackground(new JTextField().getBackground());
            }
            if(book!=null){
                this.salesTableModel.addRow(new String[]{jTextFieldBookID.getText(),book.getTitle(),jTextFieldQty.getText(),String.valueOf(book.getCost())});
                this.jTextFieldBookID.setText("");
                this.jTextFieldBookID.setBackground(new JTextField().getBackground());
                this.jTextFieldQty.setText("1");
            }
            else{
                this.jTextFieldBookID.setBackground(Color.red);
            }
        }
    }//GEN-LAST:event_jTextFieldBookIDKeyPressed

    private void jTextFieldBookIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBookIDKeyReleased
        if(this.jTextFieldBookID.getText().equals("")){
            this.jTextFieldBookID.setBackground(new JTextField().getBackground());
        }
    }//GEN-LAST:event_jTextFieldBookIDKeyReleased

    private void jTextFieldQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtyKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldQtyKeyReleased

    private void jTextFieldQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQtyFocusLost
        // TODO add your handling code here:
        if(this.jTextFieldQty.getText().equals("") || Integer.valueOf(this.jTextFieldQty.getText())<=0 ){
            this.jTextFieldQty.setText("1");
        }
    }//GEN-LAST:event_jTextFieldQtyFocusLost

    private void jTextFieldQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtyActionPerformed

    private void jTextFieldBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBookIDActionPerformed

    private void jTextFieldPurchaseIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPurchaseIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPurchaseIDKeyPressed

    private void jTextFieldPurchaseIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPurchaseIDKeyReleased
        if(jTextFieldPurchaseID.getText().equals("")){
            this.jButtonFinish.setEnabled(false);
        }
        else{
            this.jButtonFinish.setEnabled(true);
        }
    }//GEN-LAST:event_jTextFieldPurchaseIDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearAll;
    private javax.swing.JButton jButtonFinish;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPaneHistory;
    private javax.swing.JTable jTableSale;
    private javax.swing.JTextField jTextFieldBookID;
    private javax.swing.JTextField jTextFieldPurchaseID;
    private javax.swing.JTextField jTextFieldQty;
    // End of variables declaration//GEN-END:variables

    public void setUser(User user) {
        this.USER=user;
//        this.jTabbedPane1.add("history 2",new SalesHistoryJPanel(this,USER));
        fillHistoryTable();
    }


    private void finishSale(){
        ArrayList<SaleItem> list= new ArrayList<>();
        String time = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss").format(LocalDateTime.now());
        String employeeID= USER.getId();//UserManger.getLocalUser();
        int rcvIndex = SearchHelper.getLastRcvIndex()+1;
        String invoiceID = String.valueOf(SearchHelper.getLastInvoiceNumber()+1);
        for (int i =0; i<jTableSale.getRowCount(); i++){
            String id = UUID.randomUUID().toString();

            SaleItem saleItem = new SaleItem(id, jTextFieldPurchaseID.getText(),invoiceID, time,employeeID, jTableSale.getValueAt(i, 0).toString(), Integer.valueOf(jTableSale.getValueAt(i, 2).toString()),Double.valueOf(jTableSale.getValueAt(i, 3).toString()));
            
            System.out.println(jTextFieldPurchaseID.getText());
            System.out.println(saleItem.getPurchaseID());
            DatabaseHelper.addSaleItem(saleItem);
            list.add(saleItem);
            Book book=SearchHelper.getBookByID(jTableSale.getValueAt(i, 0).toString());
            book.setQty(book.getQty()-Integer.valueOf(jTableSale.getValueAt(i, 2).toString()));
            DatabaseHelper.updateBookQty(book);            
        }
        this.salesTableModel.setRowCount(0);
        this.jTextFieldPurchaseID.setText("");
//        jTabbedPaneAll.add(String.valueOf(rcvIndex),new InventoryListPanel(list));
//        allTabPanel.updateTableData(SearchHelper.getInventories());
//        addTableModel.setRowCount(0);
//        invToAddList.clear();
    }

    private void fillHistoryTable() {
        jTabbedPaneHistory.removeAll();
        List<SaleItem> list;
        if(!USER.getId().equals(MainBooksWindow.xUser)){
            list = SearchHelper.getSalesByEmployeeID(USER.getId());
        }
        else{
            list=SearchHelper.getSales();
        }
        Collections.sort(list, new Comparator<SaleItem>() {

            public int compare(SaleItem o1, SaleItem o2) {
                // compare two instance of `Score` and return `int` as result.
                return o2.getTime().compareTo(o1.getTime());
            }
        });
        
        this.jTabbedPaneHistory.add("All",new SalesHistoryJPanel(this,list));

        
        
        SortedMap<String,List<SaleItem>> salesHistoryMapByYear = SaleItem.getSalesHistoryMapByYear(list);
        
        for (SortedMap.Entry<String, List<SaleItem>> entry : salesHistoryMapByYear.entrySet()) {
            String key = entry.getKey();
            List<SaleItem> saleItems = entry.getValue();
            this.jTabbedPaneHistory.add(entry.getKey(),new SalesHistoryJPanel(this,saleItems));
        }
        this.jTabbedPaneHistory.setSelectedIndex(this.jTabbedPaneHistory.getTabCount()-1);
//        this.jTabbedPane1.add("history 2",new SalesHistoryJPanel(this,USER));
        
            
    }
}
