/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SunriseMedia;

import Books.windows.MainBooksWindow;
import org.opencv.core.Core;

public class SunriseMedia {
    public static void main(String[] args) {
        MainBooksWindow mainWindow = new MainBooksWindow();
        mainWindow.setVisible(true);
    }
}
