/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SunriseMedia;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SunriseMediaTest {
    @Test void appHasAGreeting() {
        SunriseMedia classUnderTest = new SunriseMedia();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
